#! /usr/bin/env ruby

require "pg"

def display_list_expenses
  db = PG.connect(dbname: "expense")
  
  result = db.exec("SELECT * FROM expense ORDER BY created_on ASC")
  
  headers = result.fields
  headers[0] = headers[0].rjust(3)
  headers[1] = headers[1].rjust(15)
  headers[2] = headers[2].rjust(12)
  
  puts headers.join(" | ")
  
  result.each do |tuple|
    column = [ tuple["id"].rjust(3),
               tuple["created_on"].rjust(15),
               tuple["amount"].rjust(12),
               tuple["memo"]]
    puts column.join(" | ")
  end
end

def display_help
  puts <<-HELP
    An expense recording system
  
    Commands:
  
    add AMOUNT MEMO [DATE] - record a new expense
    clear - delete all expenses
    list - list all expenses
    delete NUMBER - remove expense with id NUMBER
    search QUERY - list expenses with a matching memo field
  HELP
end

command = ARGV[0]

if command == "list"
  display_list_expenses
else
  display_help
end

